kind: pipeline
name: default

steps:
  - name: build
    image: cbrgm/drone-hugo:latest
  - name: publish
    image: cschlosser/drone-ftps
    environment:
      FTP_USERNAME:
        from_secret: ftp_username
      FTP_PASSWORD:
        from_secret: ftp_password
      PLUGIN_HOSTNAME: jeremybise.com:21
      PLUGIN_SECURE: false
      PLUGIN_VERIFY: false
      PLUGIN_SRC_DIR: /public
      PLUGIN_DEST_DIR: /httpdocs
      PLUGIN_CLEAN_DIR: true
