pipeline:
  build:
    image: cbrgm/drone-hugo:latest
    validate: true
    version: 0.47.1
  publish:
    image: plugins/s3-sync:1
    bucket: jeremybise.com
    secrets: [ aws_access_key_id, aws_secret_access_key ]
    region: us-east-1
    source: public
    target: /
