pipeline:
  build:
    image: debian:stretch
    commands:
      - apt-get update && apt-get -y install hugo python-pygments
      - hugo
  publish:
    image: plugins/s3-sync:1
    bucket: jeremybise.com
    secrets: [ aws_access_key, aws_secret_key ]
    region: us-east-1
    source: public
    target: /
