pipeline:
  build:
    image: plugins/hugo:0.47.1
    output: public
    when:
      branch: [ master ]
  publish:
    image: plugins/s3-sync:1
    bucket: jeremybise.com
    secrets: [ aws_access_key, aws_secret_key ]
    region: us-east-1
    source: public
    target: /
