pipeline:
  build:
    image: debian:stretch
    commands:
      - curl -O https://github.com/gohugoio/hugo/releases/download/v0.47.1/hugo_0.47.1_Linux-64bit.tar.gz
      - tar xzf hugo_0.47.1_Linux-64bit.tar.gz -C /usr/local/bin/
      - hugo version
      - hugo
  publish:
    image: plugins/s3-sync:1
    bucket: jeremybise.com
    secrets: [ aws_access_key, aws_secret_key ]
    region: us-east-1
    source: public
    target: /
