pipeline:
  build:
    image: alpine
    commands:
      - apk add ca-certificates
      - wget https://github.com/gohugoio/hugo/releases/download/v0.47.1/hugo_0.47.1_Linux-64bit.tar.gz
      - tar xzf hugo_0.47.1_Linux-64bit.tar.gz -C /usr/local/bin/
      - rm hugo_0.47.1_Linux-64bit.tar.gz
      - hugo version
      - hugo
  publish:
    image: cschlosser/drone-ftps
    hostname: my.thosegeeks.com
    secrets: [ ftp_username, ftp_password ]
    clear_dir: true
    dest_dir: /httpdocs
    src_dir: /public
    secure: false
