baseURL = "https://jeremybise.com/"
languageCode = "en-us"
title = "The notes of Jeremy Bise"

pygmentsCodeFences = true
pygmentsUseClasses = true
enableEmoji = true

[taxonomies]
category = "categories"

[related]
threshold = 80
toLower = true
includeNewer = true

[[related.indices]]
name = "related"
weight = 150

[permalinks]
posts = "/:title"

[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params.algolia]
vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
params = ["categories", "tags"]

[outputs]
home = ["HTML", "RSS", "Algolia"]
