baseURL = "https://jeremybise.com/"
languageCode = "en-us"
title = "The notes of Jeremy Bise"

pygmentsCodeFences = true
pygmentsUseClasses = true

[taxonomies]
    recipe = "recipes"
    note = "notes"

[related]
threshold = 80
toLower = true
includeNewer = true

[[related.indices]]
name = "related"
weight = 150
