baseURL = "https://jeremybise.com/"
languageCode = "en-us"
title = "The notes of Jeremy Bise"

pygmentsCodeFences = true
pygmentsUseClasses = true
enableEmoji = true

[author]
name = "Jeremy Bise"

[taxonomies]
category = "categories"

[related]
threshold = 80
toLower = true
includeNewer = true

[[related.indices]]
name = "related"
weight = 150

[permalinks]
posts = "/:slug"

[outputs]
home = ["HTML", "RSS", "JSON"]
section = ["HTML", "RSS", "JSON"]
