baseURL = "https://jeremybise.com/"
languageCode = "en-us"
title = "The notes of Jeremy Bise"

pygmentsCodeFences = true
pygmentsUseClasses = true
enableEmoji = true

[taxonomies]
category = "categories"

[related]
threshold = 80
toLower = true
includeNewer = true

[[related.indices]]
name = "related"
weight = 150

[context.deploy-preview.environment]
  HUGO_VERSION = "0.50"

[context.production.environment]
  HUGO_VERSION = "0.50"
