backend:
  name: github
  repo: jeremybise/jeremybise-hugo
publish_mode: editorial_workflow
media_folder: "assets/media"
public_folder: "assets/media"
collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    fields:
      - {name: "title", label: "Title", widget: "string"}
      - {name: "date", label: "Date", widget: "datetime"}
      - {name: "featured_image", label: "Featured Image", widget: "image"}
      - {name: "body", label: "Body", widget: "markdown"}
