---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: content/posts
  label: Posts
  create: all
  match: "**/*"
  templates:
  - posts
upload_dir: assets/media
public_path: "/media"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_command: hugo -E -F -D
  preview_output_directory: public
version: '0.53'
