---
new_page_extension: md
auto_deploy: true
admin_path: admin
webhook_url: 
sections:
- type: directory
  path: content
  label: Posts
  create: all
  match: "*"
upload_dir: assets/media
public_path: "/media"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
version: '0.47'
